[platformio]
src_dir = emv_physical_tester/card_inserter/firmware_esp32
 
[env:esp32dev]
platform = espressif32
board    = esp32dev
framework = arduino
 
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.6
    bblanchon/ArduinoJson    @ ^7.0.0