[env:esp32dev]
platform = espressif32
board    = esp32dev
framework = arduino

build_src_dir = emv_physical_tester/card_inserter/firmware_esp32

lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.6
    bblanchon/ArduinoJson    @ ^6.21.5
